name: Check PR title
on:
  pull_request:
    types: [ "opened", "reopened", "edited", "synchronize" ]

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd ./.github/actions/check-pr-title
          npm ci
      - name: Check PR title
        uses: ./.github/actions/check-pr-title