name: "Draft new release"

on:
  workflow_dispatch

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      # Calculate the next release version based on conventional semantic release
      - name: Create release branch
        id: create-release
        run: |
          source_branch_name=${GITHUB_REF##*/}
          current_version=$(jq -r .version package.json)
          
          npm ci
          npm run release -- --skip.commit --skip.tag --skip.changelog
          new_version=$(jq -r .version package.json)
          git reset --hard

          branch_name="release/${new_version}"

          echo "Source branch for new release is $source_branch_name"
          echo "Current version is $current_version"
          echo "New version is $new_version"
          echo "New release branch name is $branch_name"
          git checkout -b "$branch_name"
          
          echo "::set-output name=source_branch_name::$source_branch_name"
          echo "::set-output name=branch_name::$branch_name"
          echo "::set-output name=new_version::$new_version"

      - name: Update changelog & bump version
        run: |
          npm ci
          npm run release

      - name: Push new release branch
        run: git push --set-upstream origin ${{ steps.create-release.outputs.branch_name }}

      - name: Create pull request into master
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.create-release.outputs.branch_name }}
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(release): Pulling ${{ steps.create-release.outputs.branch_name }} into master"
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: ${{ github.actor }}
