name: "Publish new release"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    steps:
      - name: Extract version from branch name (for release branches)
        id: extract-version
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "::set-output name=release_version::$VERSION"

#      - name: Create Release
#        uses: thomaseizinger/create-release@1.0.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
#          tag_name: v${{ steps.extract-version.outputs.release_version }}
#          name: ${{ steps.extract-version.outputs.release_version }}
#          draft: false
#          prerelease: false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          tag_name: v${{ steps.extract-version.outputs.release_version }}
          name: ${{ steps.extract-version.outputs.release_version }}
          generate_release_notes: true

      - name: Create pull request into develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "ci: Pulling master into develop as post release step"
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: ${{ github.actor }}
